# ${project.name} - ${project.description}
# 项目地址: ${project.url}
# 下载地址: ${project.distributionManagement.downloadUrl}
version: ${project.version}

debug: false

# 统计数据设定
# 该选项用于帮助开发者统计插件版本与使用情况，且绝不会影响性能与使用体验。
# 当然，您也可以选择在这里关闭，或在plugins/bStats下的配置文件中关闭。
metrics: true

# 检查更新设定
# 该选项用于插件判断是否要检查更新，若您不希望插件检查更新并提示您，可以选择关闭。
# 检查更新为异步操作，绝不会影响性能与使用体验。
check-update: true

stroage:
  # 存储方式，可选 [ yaml | json | h2 | mysql(推荐) ]
  method: yaml

  # 选择 yaml/json 存储方式时的存储路径
  # 默认为相对路径，相对于插件生成的配置文件夹下的路径
  # 支持绝对路径，如 “/var/data/item-commands/"(linux) 或 "D:\data\item-commands\"(windows)
  # 使用绝对路径时请注意权限问题
  file-path: data

  # 选择 mysql/mariadb 存储方式时的数据库配置
  database:
    # 数据库驱动路径，默认为 MySQL
    driver: "com.mysql.cj.jdbc.Driver"
    # 数据库连接配置
    host: "127.0.0.1"
    port: 3306
    database: "minecraft"
    username: "username"
    password: "password"
    extra: "?useSSL=false"
    # 插件相关表的名称