main: cc.carm.plugin.commanditem.Main
name: CommandItem

version: ${project.version}
description: ${project.description}
website: ${project.url}

authors:
  - CarmJos

softdepend:
  - PlaceholderAPI

api-version: 1.13

commands:
  "CommandItem":
    aliases:
      - "CMDItem"
    description: "CommandItem的主要指令。"
    usage: "/CommandItem help"